ethersphere/bee-js

src/index.ts

chore: parameter properties in Bee class

---

test/utils.ts

refactor: test utility function randomBuffer is now pseudorandom

---

package-lock.json
package.json
src/index.ts
src/modules/file.ts
src/modules/tag.ts
src/types.ts
src/utils/data.ts
src/utils/error.ts
src/utils/safeAxios.ts
test/index.spec.ts
test/modules/file.spec.ts
test/modules/tag.spec.ts
test/utils.ts

This PR adds the low-level module functionality to the `Bee` class and only exposes that. Therefore passing around the url is no longer necessary because it is encapsulated in the class instance.
Also added error handling for axios responses and some helper types.
Fixes #5
The Buffers are replaced on the interface, but not internally (regarding #10)

feat: Bee class functionality with error handling

---

.eslintrc.js
.prettierrc
src/modules/file.ts
src/modules/tag.ts
test/modules/file.spec.ts

Change dangling commas and object-curly-spacing options
Fixes #20

chore: change eslint and prettier config

---

.github/workflows/check.yaml

To be merged after #35 
Resolves #31

chore: nodejs and browser compilation in ci

---

.github/workflows/ci.yaml

Enable debug for failed pipelines

test: add debug for failed pipelines

---

src/index.ts
src/modules/bytes.ts
src/modules/pinning.ts
test/index.spec.ts
test/modules/bytes.spec.ts
test/modules/file.spec.ts
test/modules/pinning.spec.ts
test/utils.ts

Add `/bytes` endpoint wrappers.

feat: bytes module

---

test/bee.sh

test: add bee cluster functionality for bee.sh

---

package-lock.json
package.json
src/modules/collection.ts
src/types/utf8-encoder.d.ts
src/utils/tar.ts
test/bee-class.spec.ts

fix: upload collection with unicode filenames

---

src/modules/collection.ts
src/utils/safeAxios.ts
test/modules/collection.spec.ts
test/modules/file.spec.ts

fix: big file upload

---

src/index.ts
src/utils/data.ts

fix: replace Buffer with Uint8Array so it's not used in browser

---

src/utils/data.ts

This is a fix for https://github.com/ethersphere/bee-js/pull/85

fix: websocket data buffer array typing

---

src/modules/debug/settlements.ts
test/modules/debug/settlements.spec.ts

This PR provides the wrapper functions around the settlements endpoints. It is part of a series of PR to provide functionality for balance and chequebooks (#68).
See also #96 and #97

feat: settlements endpoints

---

.github/workflows/check.yaml
README.md
package-lock.json
package.json
webpack.config.ts

Minifies bundle for both node and browser version on production compilation.
Also fixes compilation by adding 'utf8-validate' and 'bufferutil' packages to the dependency list.
Fixes: #76

ci: minify bundle

---

README.md

Merge after release is done: https://github.com/ethersphere/bee-js-docs/pull/9

docs: add documentation links to README

---

test/bee.sh

fix: bee.sh

---

src/modules/file.ts

fix: remove automatic content-type header on file upload

---

package-lock.json
package.json

Fixes security issue https://snyk.io/vuln/SNYK-JS-ELLIPTIC-1064899

fix: bump elliptic version to 6.5.4

---

src/bee-debug.ts
src/modules/debug/balance.ts
src/modules/debug/chequebook.ts
src/modules/debug/connectivity.ts
src/modules/debug/settlements.ts
src/types/debug.ts
src/types/index.ts
test/modules/debug/connectivity.spec.ts
test/modules/pss.spec.ts

feat: expose types for BeeDebug

---

.github/config.yaml

chore: customize BeeWorker labels names

---

src/bee-debug.ts
src/modules/debug/chequebook.ts
test/modules/debug/chequebook.spec.ts

Ok, hopefully this is the real PR that will pass all of the tests with flying colors and be able to be merged.  As the old saying goes, "no job is complete until the paperwork is done".

refactor!: correct getChequebookBalance spelling (remove extra u)

---

src/chunk/signer.ts
src/chunk/soc.ts
test/chunk/signer.spec.ts

fix: no ethereum prefix for custom signers

---

test/bee-class.spec.ts
test/utils.ts

As requested in https://github.com/ethersphere/bee-js/pull/192#issuecomment-792734775

test(feed): increase flaky feed tests timeout

---

.github/workflows/release_github.yaml

ci(release-please): before 1.x any breaking changes will bump minor

---

package.json
src/bee-debug.ts
src/bee.ts
src/index.ts
src/utils/url.ts
test/bee-class.browser.spec.ts
test/bee-class.spec.ts

fix: strip trailining slash in node url

---

src/chunk/signer.ts
src/chunk/soc.ts
src/utils/bytes.ts
test/chunk/signer.spec.ts
test/utils.ts

So I did not take the road of breaking change only expanded the flexibility of the interface and improved validation of custom Signers.
I will create follow up PR building on this one with utility for wrapping the Ethereum wallets.

feat: improved signer interface and validation

---

src/bee.ts
src/modules/pinning.ts
src/utils/hex.ts
src/utils/type.ts

fix: adding string type and assertions to Reference on API

---

src/bee.ts
src/chunk/signer.ts
src/types/index.ts
test/bee-class.spec.ts
test/chunk/signer.spec.ts
test/chunk/soc.spec.ts
test/feed/index.spec.ts

Introduce default signer for Bee instance.

feat: default signer on bee instance

---

src/chunk/bmt.ts
src/chunk/signer.ts
src/chunk/soc.ts
src/feed/index.ts
src/feed/topic.ts
src/utils/hash.ts

refactor: move hash module to util folder

---

src/chunk/cac.ts
src/chunk/soc.ts
test/chunk/cac.spec.ts
test/chunk/soc.spec.ts

Closes #150 also partly covers #211

refactor: split soc and cac tests and drop verify*

---

src/types/debug.ts

This reverts commit cf5503c578290c917a252fa80e29ccf4065620c2.
No idea how to revert properly. This should work but if anyone knows please help.

revert: "fix!: shape of the LastCashoutActionResponse (#263)"

---

README.md

docs: yarn warning for github install

---

.github/workflows/tests.yaml
README.md
test/integration/modules/debug/balance.spec.ts
test/utils.ts

test: unify integration setup

---

src/bee-debug.ts
src/modules/debug/chequebook.ts
src/types/debug.ts
src/utils/type.ts
test/integration/modules/debug/chequebook.spec.ts
test/unit/utils/type.spec.ts

fix: use bigint primitive

---

.github/workflows/tests.yaml
test/integration/feed/index.spec.ts
test/integration/modules/debug/connectivity.spec.ts
test/integration/modules/feed.spec.ts

This PR changes the environment of the JS tests to the [Bee Factory](https://github.com/ethersphere/bee-factory) docker environment.
Fixes: #298

ci: bee-factory

---

src/bee.ts
src/feed/type.ts
src/utils/eth.ts

refactor: assert guards unification

---

src/modules/debug/chequebook.ts
src/types/debug.ts

@AuHau feel free to merge it when approved and also please do rebase the #290 PR on top of it ❤️

fix: shape of `LastCashoutActionResponse` for Bee 0.6.0

---

src/bee-debug.ts
src/modules/debug/states.ts
src/types/debug.ts
test/integration/modules/debug/states.spec.ts

feat: chain and reserve state endpoints

---

src/utils/safeAxios.ts

feat: pass error message from bee to thrown error

---

.eslintrc.js
.github/workflows/tests.yaml
jest.config.ts
src/bee.ts
src/chunk/soc.ts
src/feed/index.ts
src/modules/bytes.ts
src/modules/bzz.ts
src/modules/chunk.ts
src/modules/feed.ts
src/modules/pss.ts
src/modules/soc.ts
src/modules/stamps.ts
src/types/index.ts
src/utils/headers.ts
src/utils/type.ts
test/integration/bee-class.browser.spec.ts
test/integration/bee-class.spec.ts
test/integration/chunk/bmt.spec.ts
test/integration/chunk/cac.spec.ts
test/integration/chunk/soc.spec.ts
test/integration/feed/index.spec.ts
test/integration/modules/bytes.spec.ts
test/integration/modules/bzz.spec.ts
test/integration/modules/chunk.spec.ts
test/integration/modules/feed.spec.ts
test/integration/modules/pinning.spec.ts
test/integration/modules/pss.spec.ts
test/utils.ts

Closes #309.
I am not sure if the `BatchId` should be branded or not. What do you think? 🤔

refactor: custom type for postage batch

---

src/bee.ts
src/modules/stamps.ts
src/types/index.ts

feat: expose stamps depth limits

---

package.json

chore: npm ci script

---

src/bee-debug.ts
src/bee.ts
src/chunk/signer.ts
src/feed/json.ts
src/feed/topic.ts
src/modules/tag.ts
src/types/debug.ts
src/types/index.ts
src/utils/collection.ts
src/utils/hex.ts
src/utils/type.ts
test/integration/modules/bzz.spec.ts
test/integration/modules/tag.spec.ts
test/unit/assertions.ts
test/unit/bee-class.spec.ts
test/unit/bee-debug-class.spec.ts
test/unit/feed/json.spec.ts
test/utils.ts

feat!: input validation

---

webpack.config.ts

fix: missing stream package with webpack

---

README.md
src/bee.ts
src/types/index.ts
src/utils/collection.ts
src/utils/type.ts

docs: api docs improvement

---

src/bee-debug.ts
src/bee.ts
src/chunk/signer.ts
src/modules/debug/tag.ts
src/modules/tag.ts
src/types/debug.ts
src/types/index.ts
src/utils/safe-axios.ts
src/utils/type.ts
test/integration/bee-class.spec.ts
test/integration/modules/bzz.spec.ts
test/integration/modules/debug/tag.spec.ts
test/integration/modules/tag.spec.ts
test/unit/bee-class.spec.ts
test/unit/bee-debug-class.spec.ts
test/utils.ts

feat: new tags endpoints

---

.gitignore
README.md
jest.config.ts

Now you can configure env. variable for the postage stamps so they are not created on every test run.

test: improve postage creation

---

src/bee-debug.ts
src/modules/debug/chequebook.ts
src/modules/debug/transactions.ts
src/types/debug.ts
src/types/index.ts
src/utils/type.ts

feat: pending transactions management

---

src/bee.ts
test/integration/bee-class.spec.ts

fix: remove check for pinned content in reupload

---

jest.config.ts
test/tests-setup.ts

refactor: use global setup for stamps creation in tests

---

src/types/debug.ts

feat: openapi versions in health

---

src/bee.ts
src/modules/chunk.ts
src/types/index.ts
test/integration/bee-class.spec.ts
test/unit/bee-class.spec.ts
test/utils.ts

feat: exposing chunk functionality

---

src/utils/expose.ts
src/utils/stamps.ts

feat: stamp usage utility function

---

package-lock.json

```
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
```

chore: browserlist update

---

src/types/index.ts

fix: rename DebugPostageBatch into PostageBatch

---

src/bee-debug.ts
src/modules/debug/status.ts
src/types/debug.ts

fix: rename NodesInfo into NodeInfo

---

.github/workflows/tests.yaml
package-lock.json
package.json

Closes #496 
Node 17 by default prefer IPv6 over IPv4 so it resolves `localhost` into `::1` instead of `127.0.0.1` which Bee Factory expects

feat: node 17 support

---

src/types/index.ts
src/utils/error.ts
src/utils/http.ts
test/unit/utils/http.spec.ts

feat: exposing request and response configuration on BeeResponseError

---

src/bee.ts
src/types/index.ts
test/unit/bee-class.spec.ts

feat: add owner property to SOCReader interface

---

package-lock.json
package.json
src/types/index.ts
src/types/web-streams-polyfill/index.d.ts
src/utils/stream.ts

fix: web-stream-polyfill typings

---

.github/workflows/tests.yaml
package.json
src/modules/debug/status.ts

Updated Bee version 1.5.0-dda5606e

chore: update to bee 1.5.0-dda5606e

---

.depcheckrc.json
package-lock.json
package.json
src/utils/data.browser.ts
src/utils/data.ts
test/integration/bee-class.browser.spec.ts

fix: remove browser blob polyfill for service workers support

---

src/types/debug.ts

fix: nodeinfo interface

---

.github/workflows/tests.yaml
package.json
src/modules/debug/status.ts

Updated Bee version 1.5.1-d0a77598

chore: update to bee 1.5.1-d0a77598

---

src/bee.ts
src/feed/index.ts
src/feed/retrievable.ts
test/integration/bee-class.spec.ts

feat: is feed retrievable support

---

src/bee-debug.ts
src/utils/type.ts
test/integration/bee-debug-class.spec.ts
test/unit/bee-debug-class.spec.ts

fix: no invalid amount for stamps

---

src/utils/type.ts

fix: modify the ENS validation to work in safari or older browsers

---

src/utils/http.ts

Node 18 has native `fetch` implementation called Undici. Errors from this implementation have top level generic message "fetch failed" with the more specific error placed into `cause` property. Instead of "fetch failed" we expose the underlying problem.

feat: expose underlying undici error messages

---

.github/workflows/update_bee.yaml
README.md

ci: update bee version

---

package.json
src/modules/debug/status.ts

Updated Bee version 1.6.1-364bf924

chore: update to bee 1.6.1-364bf924

---

README.md
package.json
src/modules/debug/status.ts

Updated Bee version 1.6.2-09106b54

chore: update to bee 1.6.2

---

README.md
package.json
src/modules/debug/status.ts

Updated Bee version 1.7.0-bbf13011

chore: update to bee 1.7.0

---

src/types/index.ts
src/utils/type.ts
test/integration/bee-class.spec.ts
test/unit/bee-class.spec.ts
test/utils.ts

fix!: convert cid getter to function

---

.github/workflows/tests.yaml
README.md
package.json

chore!: drop node 12 support

---

src/bee-debug.ts
src/modules/debug/stake.ts
src/types/debug.ts
src/utils/type.ts
test/integration/bee-debug-class.spec.ts
test/unit/assertions.ts
test/unit/bee-debug-class.spec.ts

feat: staking endpoint support

---

README.md
package-lock.json
package.json
src/modules/debug/stake.ts
src/modules/debug/states.ts
src/modules/debug/status.ts
src/types/debug.ts
test/integration/bee-debug-class.spec.ts

Updated Bee version 1.10.0-904cbb08

chore: update to bee 1.10.0

---

README.md
package.json
src/modules/debug/status.ts

Updated Bee version 1.11.1-rc1-fda20caa

chore: update to bee 1.11.1

---

src/utils/stamps.ts

Util fn to get the effective bytes for a depth.

feat: add stamp effective byte util

---

.npmrc

build: disable legacy peer deps
