README.md
test/bee.sh

In order to have unified test results, we need the same Bee client configuration to do tests.
This PR adds a little Bash script, which starts a Bee client with the appropriate configurations for run local tests.
extends #37

chore: add Bee client starter with Docker

---

src/index.ts
src/modules/pinning.ts
src/utils/headers.ts
test/index.spec.ts
test/modules/file.spec.ts
test/modules/pinning.spec.ts
test/modules/tag.spec.ts
test/utils.ts

This PR adds the pinning functionality for files and collections. It doesn't add the functionality for bytes and chunks because they are not part of the JS API yet.
This means that once we add the chunks functionality then we will need to add pinning for it as well and it has more endpoint than just post and delete. Regarding bytes: we may completely avoid to add it because currently it's not very different from files without a filename.

feat: pinning for files and collections

---

package-lock.json
package.json
src/index.ts
src/modules/debug/connectivity.ts
src/modules/pss.ts
src/types/index.ts
test/bee-class.spec.ts
test/modules/pinning.spec.ts
test/modules/pss.spec.ts
test/utils.ts

This PR implements the PSS send and subscribe functionality. There is also a `pssReceive` function on the Bee class to simplify the case when you want to receive just one message and it uses `pssSubscribe` internally. The WebSocket interface is not exposed on the public interface because I find it too cumbersome and error-prone to use. Instead a `PssMessageHandler` type is defined for recieving messages and error and a `PssSubscription` type is defined to provide cancel functionality on the subscription.
For this functionality we also need to access the debug API to get access to the overlay address and pssPublicKey. I added a DebugBee class temporarily to support this however I expect that on the long term these will move to a private API and its configuration may effect how we construct …

feat: pss send and subscribe

---

src/index.ts
src/modules/chunk.ts
src/modules/pinning.ts
src/modules/pss.ts
src/types/index.ts
test/modules/chunk.spec.ts
test/modules/pinning.spec.ts
test/utils.ts

This PR implements the endpoints related to chunks (chunk upload, download and pinning). It only adds at the module level because at the `Bee` class level I plan to add higher level functionality (e.g. Chunk interface instead of  `Uint8Array`s).
The upload API is quite strange that it already requires the hash to be calculated in order to be able to upload. Since this functionality was not yet added, I hardcoded some pre-calculated values in the upload and download test.
The chunk pinning API has a few extra functions compared to the other (bytes, fiels, collection) APIs and testing it is a bit difficult with only having hardcoded values because this way the tests affect each other. I plan to change that in the next iteration when we are able to create (pseudo-)random chunks, in this PR …

feat: chunk API module

---

test/bee.sh

at issue #62 turned out the script which is provided to run local tests in cluster, after a while, run out of the balance.
it fixes that problem by adding the maximum possible amount of payment tolerance value for the `queen` node.

fix: raise payment tolerance on tests

---

.eslintrc.js
.prettierrc

There were some problems with the eslint/prettier configuration, that prevented to do auto-formatting.
this PR solves this problem

style: add prettier autoformats to eslint

---

package-lock.json
package.json

We don't use `patch-package` and causes error on npm install currently.
This PR removes this dependency

fix: remove postinstall

---

test/modules/collection.spec.ts
test/modules/file.spec.ts

The tests for uploading big files sometimes took longer than the default timeout so I increased the timeouts for these two tests.

test: increase big upload timeout

---

package-lock.json
package.json
src/types/utf8-encoder.d.ts
src/utils/tar.ts

I just realized that for fixing the unicode path for uploading an extra dependency was added which is not necessary. This PR removes the `utf8-encoder` package and uses the standard [TextEncoder](https://developer.mozilla.org/en-US/docs/Web/API/TextEncoder) API instead.

fix: remove utf8-encoder package dependency

---

src/index.ts
src/modules/collection.ts
src/modules/file.ts
src/utils/data.ts
src/utils/file.ts
test/bee-class.spec.ts

feat: uploadFile support for File type

---

.github/workflows/ci.yaml

As per the nodejs release cycle, we should support node v15 as well https://nodejs.org/en/about/releases/

ci: add node v15 as test target

---

src/modules/debug/balance.ts
test/modules/debug/balance.spec.ts

Part of #68 
Adds the `/balances` and `/consumed` endpoints described here: https://docs.ethswarm.org/debug-api/#tag/Balance

feat: balances and consumed endpoint

---

.github/workflows/ci.yaml
src/modules/debug/chequebook.ts
test/modules/debug/chequebook.spec.ts
test/utils.ts
test/utils/hex.spec.ts

Part of #68
This PR provides the wrapper functions around the chequebook endpoints. Not all of them have tests because it is not trivial to create the conditions required because of the stateful nature of the functionality.
Also it's not trivial to run the tests locally because they require at least one Bee node running with `swap-enable` set to true and our test runner script currently doesn't do that. The chequebook tests now check if the `BEE_CHEQUEBOOK_URL` environment variable is set and if it's not then those tests are skipped and a message is printed to the console informing about the situation. This environment variable is set when the tests are running on github because there the test runners have `swap-enable` set.
Please note that this functionality is not yet exposed on the …

feat: chequebook api

---

.github/workflows/ci.yaml
test/modules/debug/chequebook.spec.ts
test/utils.ts

Before the environment variable had to set to a url of a node with `swap-enable`. Now we just check if the `BEE_TEST_CHEQUEBOOK` environment variable is set or not and run the tests on the debug url.

refactor: rename BEE_CHEQUEBOOK_URL to BEE_TEST_CHEQUEBOOK

---

README.md
package.json
src/index.ts
test/bee-class.browser.spec.ts
test/bee-class.spec.ts
test/testpage/.gitignore
test/testpage/testpage.html
test/testpage/testpage.ts
webpack.config.ts

* Remove default `Bee` class export
* Rename library name from `@ethersphere/bee-js` to `BeeJs`.
* Update README with correct library usage examples.
* Simplify browser tests, remove its specific build
Fixes: #109 #99

refactor: library import

---

src/utils/headers.ts

Temporary workaround for #86
The `Content-Disposition` header missing should not cause exception especially since Bee does not set `Access-Control-Expose-Headers` for this header. Therefore, whenever is Bee accessed from a different origin (including different port), any file downloading method would fail. Having Bee run on a different origin is very common during development. Arguably, this header missing should never be a reason for file download methods to fail.

fix: missing content-disposition causes failure

---

.github/workflows/ci.yaml
.vscode/launch.json
README.md
test/bee-class.browser.spec.ts
test/utils.ts

* change `BEE_URL` to `BEE_API_URL` as it represents the API endpoint of the Bee client.
* change `BEE_PEER_URL` to `BEE_PEER_API_URL`
* should be refactored the debug url handling (introduce `BEE_DEBUG_URL` or something similar),
* also seems a good idea to change default fallback values of these URL variables to a more straightforward one (e.g. `http://localhost:1633` on `BEE_API_URL` and `http://localhost:11633` on `BEE_PEER_API_URL`

refactor: change bee url env

---

.eslintrc.js
src/bee.ts
src/modules/bytes.ts
src/modules/chunk.ts
src/modules/collection.ts
src/modules/file.ts
src/modules/soc.ts
src/types/index.ts
test/bee-class.browser.spec.ts

On uploading and downloading big files would be nice to provide `onProgress` to keep track with the uploading/downloading and configurate other request related options.
`bee-js` make HTTP requests by `axios`, so this PR simply exposes its options on related functions and methods. 
Resolves #133

feat: axios options

---

src/modules/debug/chunk.ts
test/bee-class.spec.ts
test/chunk/soc.spec.ts
test/feed/index.spec.ts
test/modules/feed.spec.ts
test/utils.ts

Add functionality to delete chunks from local storage to make tests repeatable. Also add helper functions for tests to ignore certain errors.
This PR is forked from `feat/feed-interface` not from master to make the review easier. Once it is approved it will be merged back to it, then that can be merged back to master.

fix: upload SOC twice

---

src/bee-debug.ts
test/modules/debug/connectivity.spec.ts

feat: expose the getPeers function on `BeeDebug`

---

src/bee-debug.ts
src/bee.ts
src/chunk/signer.ts
src/feed/index.ts
src/feed/topic.ts
src/modules/bytes.ts
src/modules/collection.ts
src/modules/feed.ts
src/modules/file.ts
src/types/index.ts
src/utils/eth.ts
src/utils/hex.ts
test/bee-class.spec.ts
test/bee.sh
test/chunk/signer.spec.ts
test/feed/index.spec.ts
test/modules/collection.spec.ts
test/modules/debug/chequebook.spec.ts
test/modules/feed.spec.ts
test/utils.ts
test/utils/hex.spec.ts

Supersedes #201 PR.
Breaking changes:
- `HexString` type is considered as non-prefixed hex string and all functions using it are expecting to have it like that. If used on public API, then it should be sanitized with `makeHexString` function
- dropped `stripHexPrefix` in favor of `makeHexString`
- Hex utility functions no longer take `withPrefix: boolean` flag as they always output non-prefixed hex and instead take `len?: number` to assert expected length of the non-prefixed hex string
- `Topic` type was changed from `Bytes` into `HexString`

feat!: hex string length support

---

src/bee.ts
src/modules/bytes.ts
src/modules/collection.ts
src/modules/file.ts
src/types/index.ts
src/utils/bytes.ts
test/utils/bytes.spec.ts

Closes #191 
Once approved, I will create follow up PR to `bee-js-docs` changing the docs.

feat: data helpers for downloaded bytes

---

.github/workflows/tests.yaml
test/bee-class.spec.ts

Fixes CI to correctly use the specified node versions. Up till now it was running on the Github's NodeJS default version (v14).

ci: use different node versions

---

test/bee.sh
test/feed/index.spec.ts
test/modules/bytes.spec.ts
test/modules/chunk.spec.ts
test/modules/collection.spec.ts
test/modules/feed.spec.ts
test/modules/file.spec.ts
test/modules/pinning.spec.ts
test/utils.ts

- increase the amount of nodes spawned by `test/bee.sh` script to 5 which matches the CI
- increased timeout for tests with big files (it just takes longer now for some reason - maybe worse performing CI machine)
- increased timeout for tests which test failure (e.g. downloading non existing file, pining non existing collection). All these seem to now hit some internal timeout and probably should be consulted with Bee devs
Mind you, the test are probably not run correctly against specific release. #229 should fix it but I wanted to keep these PRs separate

test: increased timeouts for tests testing failure and big files

---

.github/workflows/tests.yaml

Seems that in past we always used `latest` tag as the `sed` did not work. I introduced this with #193

ci: using specific version of the bee node for tests

---

src/utils/eth.ts
test/utils/eth.spec.ts

Currently, the target of the PR is `feat/improved-signer` as I was not able to merge the original PR. I will rebase it once it is merged.
It is a draft as I will verify its functionality on the Metamask signing example first.

feat: ethereum wallet signer utility

---

src/bee.ts
src/chunk/signer.ts
src/chunk/soc.ts
src/feed/index.ts
src/feed/topic.ts
src/modules/feed.ts
src/types/index.ts
src/utils/eth.ts
test/feed/index.spec.ts

Closes #214 
This moves several types spread around files into `types/index.ts` as this is exposed on root level and hence is accessible to user, but more importantly it is exposed to `typedoc` generation process so these types will be documented in API Reference.

feat: expose external types

---

CODEOWNERS

This enables the GitHub's Code Owners feature. I am not sure if this will actually work as per their documentation this file should be setup by admin/owner of the repo.
https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners

chore: codeowners specification

---

src/chunk/cac.ts
src/chunk/signer.ts
src/chunk/soc.ts
src/feed/index.ts
src/feed/topic.ts
src/utils/bytes.ts
src/utils/eth.ts
test/chunk/cac.spec.ts
test/chunk/signer.spec.ts
test/chunk/soc.spec.ts
test/feed/index.spec.ts
test/utils.ts

Closes #211 
This is work I had in progress already since last week, so I have wrapped it up as it was getting rather stale.
I have refactored the `verify*` functions into `assert*` functions. Since this is already breaking change for example thanks to the `verifyBytes()` refactor, I took the liberty and also changed the order of the parameters in some of the functions as I believe that the order should follow two guidelines:
1. Order of significants
2. Modifiers should come after the subject. E.g. if we are asserting bytes length, this is basically saying "assert that bytes under variable `data` (first parameter) should have length `20` (second parameter)" instead of the current approach that follows more "assert that length `20` (first parameter) is matching variable `data` (second …

refactor!: verify to assert

---

package-lock.json
package.json
src/modules/debug/balance.ts
src/modules/debug/chequebook.ts
src/modules/debug/settlements.ts
src/types/axios/index.d.ts
src/types/debug.ts
src/utils/safeAxios.ts
test/integration/modules/debug/balance.spec.ts
test/integration/modules/debug/chequebook.spec.ts
test/integration/modules/debug/settlements.spec.ts

So I have wrapped the BigInt work. I have introduced a custom `forceBigInt` config flag for the `safeAxios` call that runs the parsing with `JsonBigNative.parse()` in a way that all numbers are converted to BigInt no matter if they exceeded the threshold or not. This is important to have a consistent API. If this flag is not specified then only values exceeding the threshold are converted to `BigInt`.
Closes #254.

fix: use bigint for bzz amounts

---

src/types/debug.ts

Fixes #260
**NOTE: Until phase 2 of #249 we can not test this on CI**. Here is a JSON that it returns to me locally:
`http://localhost:1635/chequebook/cashout/dc830656350927d57be37dea90834f79d40cf4d4574746be0129496089d49bfc`
```JSON
{
"peer": "dc830656350927d57be37dea90834f79d40cf4d4574746be0129496089d49bfc",
"lastCashedCheque": {
"beneficiary": "0xD2fCA1F348b35E869490435e6C2eFf3996624D64",
"chequebook": "0x2689Cc943FEC13655869B716A8F2cAd8C32AdD0B",
"payout": 178765000000000
},
"transactionHash": "0x7a25acca4d248de3f87594f52e78d7f325ddd8428d4abee4468e458b5b8ff94f",
"result": {
"recipient": "0x05f26c4838be44528ec6fd4a4a31bb7f39296dfb",
"lastPayout": 0,
"bounced": false
},
"uncashedAmount": 0
}
```

fix!: shape of the LastCashoutActionResponse

---

.eslintrc.js
commitlint.config.js

@nugaon raised in the https://github.com/ethersphere/bee-status/pull/35 PR that the linter configuration is different in each project and that the swarm-cli and swarm-extension have newer rules resolving some eslint<->prettier clashes.
1. I tried to update the bee-js rules but now there actually are clashes. Can someone else try?
2. Once clashes are resolved and we agree on the rules here, I'll propagate them to other repos.

style: propagated linter rules that have been changed in swarm-cli and extension

---

test/bee.sh

just a simple fix so i can through the process, nice work guys ;D

test: fixes missed escape character in `test/bee.sh`

---

.github/workflows/check.yaml
package.json
test/integration/modules/debug/connectivity.spec.ts
test/integration/modules/pss.spec.ts
test/utils.ts
tsconfig.test.json

Creates new npm script `check:types` that runs types check also for test folder. Unfortunately, I had to create a new `tsconfig` file that extends our original one and adds the `test` folder.
I have also removed building of the source code for node and browser from GitHub Workflow because I believe it does not detect anything meaningful and only takes unnecessary time.
Closes #257

fix: check typings for test folder

---

.github/config.yaml

This creates release checklist that is passed into release PRs by [bee-runner](https://github.com/ethersphere/bee-runner/pull/5), that we defined as our release process.
The communication points are left out here as it is Attilas responsibility.

chore: define release checklist

---

src/bee.ts
src/feed/json.ts
src/types/index.ts
src/utils/eth.ts
src/utils/hex.ts
test/integration/bee-class.spec.ts
test/unit/bee-class.spec.ts
test/unit/feed/json.spec.ts
test/unit/nock.ts
test/utils.ts

This address the shortcoming of design of `getJsonFeed` that required always to have the private key for fetching the data even if it is not required and basically it disallowed to fetch other's users feed data.

fix: support address option for getJsonFeed

---

src/bee-debug.ts
src/types/index.ts
src/utils/type.ts

Refactor that I need for postage stamp work. Strictly types `Address` type to `HexString`.

refactor: address type is strict hexstring

---

src/bee.ts
src/modules/pinning.ts
src/types/index.ts
test/integration/bee-class.browser.spec.ts
test/integration/bee-class.spec.ts
test/integration/modules/pinning.spec.ts

Closes #292 
Breaking changes:
- Following methods are removed `bee.pinFile()`, `bee.unpinFile()`, `bee.pinCollection()` `bee.unpinCollection()`, `bee.pinData()`, `bee.unpinData()`, `bee.pinChunk()`, `bee.unpinChunk()`, `bee. getChunkPinningStatus()`

refactor: new pinning api

---

src/types/debug.ts
test/integration/bee-class.browser.spec.ts
test/integration/bee-class.spec.ts
test/integration/modules/debug/chequebook.spec.ts
test/integration/modules/debug/connectivity.spec.ts
test/integration/modules/debug/settlements.spec.ts
test/integration/modules/pss.spec.ts

Closes #294.
Breaking changes:
- Following properties were converted from snake_case to camelCase:
- `BeeDebug.getNodeAddresses()`: `public_key`, `pss_public_key`
- `BeeDebug.getChequebookAddress()`: `chequebookaddress`
- `BeeDebug.getAllSettlements()`: `total_received`, `total_sent`

refactor!: camelCasing of some properties

---

.github/workflows/tests.yaml

for current 0.6.0 compatbility the CI will update its env parameters to the followings:
- BEE_VERSION="0.6.0-c1e87ce-dirty" 
- BLOCKCHAIN_VERSION="1.1.1"

ci: bee factory parameters

---

README.md

This PR uses an invite link for Discord, so that people can join

docs: changed mattermost link to discord

---

src/bee.ts
src/modules/stamps.ts
test/unit/bee-class.spec.ts

When implementing the Postage batch support I forgot that depth is limited to at least 16. This adds a check for this.

feat: limit postage depth

---

src/bee.ts
src/modules/stamps.ts

No idea how to test this since the tests are in random order and I can not guarantee there is no postage stamp, right?

fix: if there are no postage stamps the getAllPostageBatch should return []

---

src/bee-debug.ts
src/modules/debug/chequebook.ts
src/types/debug.ts
src/types/index.ts
test/unit/bee-class.spec.ts
test/unit/bee-debug-class.spec.ts
test/unit/nock.ts

Closes #310 
Honestly, I would like to refactor the `cashoutLastCheque` to return the `transactionHash` directly and not wrapped in an object as is now, but it would be breaking change. What do you think?

feat!: support gas price and limit for cashout

---

src/bee.ts
src/modules/bzz.ts
test/integration/bee-class.spec.ts
test/integration/modules/bzz.spec.ts

feat: reupload

---

src/bee-debug.ts
src/modules/debug/chequebook.ts
src/types/debug.ts
test/integration/modules/debug/chequebook.spec.ts
test/unit/bee-debug-class.spec.ts
test/unit/nock.ts

Adds support for https://github.com/ethersphere/bee/pull/1812

feat: gas price for deposit and withdraw tokens

---

src/bee.ts
src/chunk/soc.ts
src/feed/index.ts
src/feed/json.ts
src/modules/chunk.ts
src/modules/soc.ts
src/types/index.ts
test/integration/bee-class.spec.ts
test/integration/chunk/bmt.spec.ts
test/integration/chunk/cac.spec.ts
test/integration/chunk/soc.spec.ts
test/integration/feed/index.spec.ts
test/integration/modules/chunk.spec.ts
test/integration/modules/feed.spec.ts
test/integration/modules/pinning.spec.ts
test/unit/feed/json.spec.ts

refactor!: no single-property object returned

---

src/utils/hooks.ts
test/unit/nock.ts
test/unit/utils/hooks.spec.ts

I got the wrong idea about the axios's headers object structure which lead to no headers reported for the request hook.

fix: provide all request headers

---

src/utils/expose.ts
test/unit/utils/collection.spec.ts

refactor!: utility module flatting and limiting

---

src/bee-debug.ts
src/bee.ts
src/feed/json.ts
src/types/debug.ts
src/types/index.ts
src/utils/type.ts
test/unit/assertions.ts
test/unit/bee-class.spec.ts
test/unit/bee-debug-class.spec.ts

Closes #392 and also allows setting custom `fetch` instance which will be needed for the upload progress support.

feat: request options

---

webpack.config.ts

> If the default webpack minimizer has been overridden (such as to customise the terser-webpack-plugin options), make sure to configure its replacement with `sourceMap: true` to enable SourceMap support.
_Source: https://webpack.js.org/configuration/devtool/_

fix(build): sourcemap

---

package.json

Packages `bufferutil` and `utf-8-validate` are peer dependencies of `ws` package so they should be installed accordingly.

build: limit published scope of files

---

src/utils/stream.ts

Currently, when we are converting Node's `Readable` to `ReadableStream` thanks to `node-fetch` the chunks are actually `Buffer`s even though in types we are proclaiming that they are `Uint8Arrays`. This fixes this by converting Buffer to `Uint8Array`.

fix: convert buffer to uint8array for readablestream

---

src/types/index.ts
src/utils/headers.ts
test/integration/bee-class.spec.ts

Closes #482 
I am not sure how to properly test the direct upload behavior. The only idea I have is to upload large quantity of data and measure the time difference between the deferred and non-deferred uploads, but even that might not work for bee-factory setup so I have opted only to verify that the upload will not fail with the direct upload instead.

feat: direct upload support

---

src/chunk/bmt.ts
src/chunk/signer.ts
src/utils/eth.ts
src/utils/hash.ts

@Cafe137 identified that when used the new 3.3.0 released in Node and ESM it will fail as:
```
> gateway-watch@1.0.0 start
> node --experimental-modules --es-module-specifier-resolution=node index.js
file:///Users/aron/Code/gateway-watch/node_modules/@ethersphere/bee-js/dist/mjs/utils/hash.js:1
import { keccak256 } from 'js-sha3';
^^^^^^^^^
SyntaxError: Named export 'keccak256' not found. The requested module 'js-sha3' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:
import pkg from 'js-sha3';
const { keccak256 } = pkg;
```
This should fix this.

fix: use default import styles for esm compatibility

---

build-fixup
package-lock.json
package.json
src/utils/stream.ts

This PR makes the `readable-stream` dependency optional. It is needed only when `Utils.readableWebToNode()` function is used in browsers.
I have debugged this and verified with new example `browser-stream` that is placed here: https://github.com/ethersphere/examples-js/pull/26 and will be merged once the `bee-js@3.3.1` is out.

fix: making readable-stream optional

---

.depcheckrc.json
package-lock.json
package.json
src/modules/debug/status.ts
src/types/web-streams-polyfill/index.d.ts
src/utils/stream.ts

Potentially superseeds the #561 with using Babel to add the `.js` suffix and hopefully still functional tests.
Closes #555

fix: add js suffix in imports for esm support with babel

---

build-fixup
package.json
src/utils/stream.ts

I have realized that it does not really make sense to have `readable-stream` as peerDependency, because if the user would want to use it in the browser, then it would have to polyfill `process` and `buffer` packages, so we can just simplify the request to actually polyfill the `stream` package directly and simplify the code around.

fix: drop readable stream

---

src/chunk/cac.ts
src/chunk/soc.ts
src/feed/identifier.ts
src/feed/index.ts
src/types/index.ts
src/utils/bytes.ts
src/utils/reference.ts
test/integration/bee-class.spec.ts
test/integration/feed/index.spec.ts
test/utils.ts

This refactor mainly aims on simplifying the `feeds/index.ts` file and it does so with:
- deduping generic constants using already existing ones in the `types/index.ts` file
- creating `BytesReference` type that handles references in bytes
- moving chunk specific functions into more appropriate places
- Splitting identifier functionality into separate file

refactor: simplifying feeds component

---

package.json
src/modules/debug/status.ts
src/types/debug.ts
test/integration/modules/debug/states.spec.ts

Updated Bee version 1.6.0-6ceadd35

chore: update to bee 1.6.0-6ceadd35

---

README.md

The dependency status badge is almost always broken for me. This gives the impression that the project is unmaintained. I think it would be better to remove it (also applicable for other projects).

docs: remove dependency status badge

---

src/bee-debug.ts
src/modules/debug/states.ts
src/types/debug.ts
test/integration/bee-debug-class.spec.ts

feat: wallet endpoint support

---

package-lock.json
package.json
src/bee.ts
src/types/index.ts
src/utils/type.ts
test/integration/bee-class.spec.ts
test/unit/bee-class.spec.ts
test/utils.ts

Closes #648 
The Feed CID is not returned for the `Bee.createFeedManifest()` as that would be breaking change. It is planned for the next breaking release.

feat: cids support

---

src/bee-debug.ts
src/types/index.ts
src/utils/type.ts
test/integration/bee-debug-class.spec.ts
test/utils.ts

feat: support for waiting on stamp to be usable

---

src/bee-debug.ts
src/utils/sleep.ts
test/integration/bee-class.spec.ts
test/integration/bee-debug-class.spec.ts
test/integration/modules/debug/chequebook.spec.ts
test/utils.ts

So... 😅
My IDE was trigger-happy and I haven't noticed it. When implementing the `waitForUsable` feature, I have copy&pasted Aron's solution, which used the `sleep` function and IDE noticed that we have this function in `test/utils.ts` file so it just imported that and I have not noticed that.
Thanks to this the `tsc` compilation changed the structure of the compiled files as it has to now import something from `./test` folder and so it changed the `./dist/cjs/` folder structure into containing subfolders `src` and `test` as this:
```
cjs
├── package.json
├── src
│   ├── bee-debug.js
│   ├── bee.js
│   ├── chunk
│   ├── feed
│   ├── index.js
│   ├── modules
│   ├── types
│   └── utils
└── test
└── utils.js
```
This, unfortunately, breaks the package as the entry file `./dist/cjs/index.js` …

fix: move sleep to have all code in src

---

src/modules/debug/connectivity.ts
src/modules/debug/stamps.ts
src/modules/pinning.ts
src/types/debug.ts

**Important: we decided to not merge this until next API breaking change.** The reasoning is, that the current bee-js works both for Bee v1.4 and v1.5 and by merging this PR we would stop supporting bee v1.4.
The bee v1.5.0 replaces the null responses with empty arrays on successful requests that have no result. With bee-js we have been already returning empty arrays for such responses but now we no longer need to do this check.
https://github.com/ethersphere/bee/pull/2821

chore: update to the bee api SwarmCommon v2 and Swarm v3

---

src/feed/index.ts

Currently, if one tries to download index 0, like so:
`await ourReader.download({ index: 0 });`
instead of downloading index 0, it will download the last index, because 0 is falsy value in JavaScript. I think we need to check if the index is 0, because in that case, we shouldn't go into the if-condition.

fix: allow feed index to be 0 when downloading

---

src/feed/index.ts
test/integration/feed/index.spec.ts

https://github.com/ethersphere/bee-js/issues/904

fix: add index param

---

src/bee.ts
src/chunk/soc.ts
src/feed/index.ts
src/feed/json.ts
src/modules/bytes.ts
src/modules/bzz.ts
src/modules/chunk.ts
src/modules/grantee.ts
src/modules/soc.ts
src/types/index.ts
src/utils/headers.ts
src/utils/http.ts
test/integration/modules/bzz.spec.ts
test/integration/modules/chunk.spec.ts
test/integration/modules/grantee.spec.ts
test/shape/shape.spec.ts
test/unit/utils/http.spec.ts
test/utils.ts

This PR add the bee new "ACT" feature to bee-js.
- Modified endpoint: `bzz`
- New endpoint: `grantee`
- `UploadResult` extended with `history_address`
- breaking changes!: `soc` and `chunk` uploads return `UploadResult` instead of `Reference`

feat(act)!: add ACT to bee-js

---

src/bee.ts
src/types/debug.ts

- `/debug-api/` ->`/api/`
- `{id`} -> `{batchid}`

fix: wrong JSDoc links
